language: node_js

node_js:
  - "8.9.4"

sudo: true

env:
  - CXX=g++-4.8 NODE_API_DB_HOST=localhost NODE_API_DB_USERNAME=express NODE_API_DB_PASSWORD=express NODE_API_DB_PORT=5432 NODE_API_DB_NAME_TEST=express
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE express;" -U postgres
  - node_modules/.bin/sequelize db:migrate
